### ISSUE TITLE
On Windows7 not working. windows7上无法正常启动。

### ISSUE THREAD

**Issue by MiyamuraMiyako** [View12138/ViewFaceCore#1]
windows 10上一切正常，但是win7上会报DllNotFoundException异常。
```log
应用程序: FaceDemo.exe
Framework 版本: v4.0.30319
说明: 由于未经处理的异常，进程终止。
异常信息: System.DllNotFoundException
   在 ViewFaceCore.Plus.ViewFacePlus32.SetModelPath(Byte[])
   在 ViewFaceCore.Plus.ViewFacePlus32.SetModelPath(System.String)
   在 ViewFaceCore.Sharp.ViewFace..ctor(System.String)
   在 ViewFaceCore.Sharp.ViewFace..ctor()
   在 FaceDemo.FormMain..ctor(System.String[])
   在 FaceDemo.Program.Main(System.String[])

```

**Comment by MiyamuraMiyako** [comment]
我刚直接调用了视拓的dll，报了一个0xc000001d，我估计是我那台设备cpu太旧了，不支持某些新指令集导致的。

**Comment by daguzt** [comment]
> 估计是我那台设备cpu太旧了，不支持某些新指令集导致的。

请问这个你有什么解决方案吗？我这边也是比较旧的电脑跑不起来

**Comment by MiyamuraMiyako** [comment]
@daguzt 已在视拓的issue下回复

**Comment by daguzt** [comment]
@MiyamuraMiyako 有一台电脑删掉原来的tennis.dll并将原来的tennis_pentium.dll改名为tennis.dll就可以启动示例程序了，但是其它的老电脑用同一操作还是不行。我以为是指令集的问题，下了个cpu_z看看，都有SSE指令集啊。。其中有一台不能启动的老电脑跟那台重命名DLL就能启动的电脑比较CPU就差了一个SSE4.2指令集，但是也有其他SSE指令集啊。。不知道是不是SSE4.2的问题，还是其他问题，就这么几台旧电脑没办法验证。。

**Comment by MiyamuraMiyako** [comment]
@daguzt 是不是系统缺vcrt

**Comment by daguzt** [comment]
@MiyamuraMiyako 电脑环境都装了vcredist x64.exe，vcredist x86.exe，.net framework 4.6.1。应该有的吧

**Comment by MiyamuraMiyako** [comment]
@daguzt 问问官方吧，我不清楚了

**Comment by daguzt** [comment]
@MiyamuraMiyako 好的，麻烦了

**Comment by daguzt** [comment]
我这边的电脑现在都能运行示例程序了，包括了一台奔腾的，应该都有sse指令集，解决方法：一，删掉原来的tennis.dll并将原来的tennis_pentium.dll改名为tennis.dll；二，下个最新的pc版qq。。安装后卸载了也可以。。现在还不知道qq加了什么东西。。
