### ISSUE TITLE
FaceDetector 与 FaceTrack 检测结果不一致

### ISSUE THREAD

**Issue by MiyamuraMiyako** [View12138/ViewFaceCore#10]
从摄像头获取的同一张图，FaceTrack取不到人脸。
![剪贴板图片](https://user-images.githubusercontent.com/10345361/99186800-c55cd700-278d-11eb-8851-7459e6958f6d.jpg)

**Comment by MiyamuraMiyako** [comment]
TrackerConfig.FaceSize为80，TrackerConfig.Stable设为false与true均不行。
测试用的FaceType与MarkType均为Normal。

**Comment by View12138** [comment]
尝试把 TrackerConfig.FaceSize调小 比如 20 MarkType应该使用MarkType.Light

**Comment by MiyamuraMiyako** [comment]
@View12138 我刚刚突然想到输出了一下日志，发现报这个。
`log
FATAL: Track Input unsupported image size (640, 480) vs. (388, 480) expected.
FaceTrackSize	 Error:Track Input unsupported image size (640, 480) vs. (388, 480) expected.
`

另外FaceSize改成20并MarkType改成Light无效且

**Comment by MiyamuraMiyako** [comment]
@View12138 我问了视拓的人，他们说：`track需要初始化的时候，设定好跟踪的图像分辨率。之后所有输入帧必须和这个设定的分辨率一样。`不知道有没有帮助？

**Comment by MiyamuraMiyako** [comment]
我找到问题了，我程序启动时读取的照片跟摄像头的照片尺寸不一致。track照片时的尺寸，似乎也被用于后续摄像头的track，就导致报了`Track Input unsupported image size (640, 480) vs. (388, 480) expected. `这么个错。

继续追查，我使用了`ChangeSize`这个扩展方法，看注释是把图片缩放放进指定尺寸的画布中，但实际生成的图片尺寸不是指定的尺寸。这里应该是问题源头。

**Comment by MiyamuraMiyako** [comment]
我数学一般，不过这个方法可以获得期望的图片尺寸

```C#
private Bitmap ChangeSize(Bitmap origin, int width, int height, bool destoryOrigin)
{
	Bitmap dest = new Bitmap(width, height);

	using (Graphics g = Graphics.FromImage(dest))
	{
		g.InterpolationMode = InterpolationMode.HighQualityBicubic;
		g.SmoothingMode = SmoothingMode.HighQuality;
		//
		var sW = origin.Width;
		var sH = origin.Height;
		var dW = 0;
		var dH = 0;

		if (sW < width && sH < height)
		{
			dW = width;
			dH = dW * sH / sW;
		}

		if (dH > height)
		{
			dH = height;
			dW = sW * height / sH;
		}

		g.DrawImage(origin, new Rectangle((width - dW) / 2, (height - dH) / 2, dW, dH), new Rectangle(0, 0, sW, sH), GraphicsUnit.Pixel);
	}
	if (destoryOrigin)
	{
		origin.Dispose();
	}
	return dest;
}
```

**Comment by View12138** [comment]
在 View.Drawing.Extensions 命名空间下有一个 System.Drawing.Image 的扩展方法  ChangeSize(Size, bool); 可以修改图像大小，这个包已经默认被 ViewFaceCore 引用，只要添加命名空间就可以直接使用。

**Comment by View12138** [comment]
> 我找到问题了，我程序启动时读取的照片跟摄像头的照片尺寸不一致。track照片时的尺寸，似乎也被用于后续摄像头的track，就导致报了`Track Input unsupported image size (640, 480) vs. (388, 480) expected. `这么个错。
> 
> 继续追查，我使用了`ChangeSize`这个扩展方法，看注释是把图片缩放放进指定尺寸的画布中，但实际生成的图片尺寸不是指定的尺寸。这里应该是问题源头。

这个方法是按照原图的宽高比例进行缩放，所以实际尺寸和指定的尺寸有一定的差异。

**Comment by View12138** [comment]
> @View12138 我问了视拓的人，他们说：`track需要初始化的时候，设定好跟踪的图像分辨率。之后所有输入帧必须和这个设定的分辨率一样。`不知道有没有帮助？

谢谢，有帮助的。我刚刚看了代码，在 FaceTrack 的时候会使用第一次传入的图片的尺寸来初始化分辨率，在 ViewFace 的实例未被销毁之前，在后续使用 FaceTrack 时都会采用第一次传入的分辨率。
这算是一个 Bug 。待后续修复。
