### ISSUE TITLE
tennis.dll文件读取

### ISSUE THREAD

**Issue by daguzt** [View12138/ViewFaceCore#11]
貌似程序运行起来后只会读取tennis.dll文件，其它例如tennis_haswell.dll，tennis_pentium.dll，tennis_sandy_bridge.dll不会根据不同cpu的指令集去动态读取，只能修改文件名将之改tennis.dll才能去适应不同硬件环境，比如奔腾的机器就要将tennis_pentium.dll改名为tennis.dll程序才能跑起来，请问有什么好的方法去解决这个问题呢？

**Comment by View12138** [comment]
这个暂时没有解决办法, 只能手动修改名称了
