### ISSUE TITLE
调用会随机报错

### ISSUE THREAD

**Issue by ygiu123** [View12138/ViewFaceCore#12]
托管调试助手 "FatalExecutionEngineError":“运行时遇到了错误。此错误的地址为 0x2f767932，在线程 0x1ba0 上。错误代码为 0xc0000005。此错误可能是 CLR 中的 bug，或者是用户代码的不安全部分或不可验证部分中的 bug。此 bug 的常见来源包括用户对 COM-interop 或 PInvoke 的封送处理错误，这些错误可能会损坏堆栈。”

**Comment by ygiu123** [comment]
大哥能不能留个联系方式，有偿请教

**Comment by View12138** [comment]
yangwei169@live.com

**Comment by Protears** [comment]
这个问题如何解决？我测试时每次调用检测480p图片都会提示这个这个错误，以下是我的测试代码：
` private static void TestFaceDetector()
        {
            ViewFace _viewFace = new ViewFace();
            Bitmap bitmap = (Bitmap)Image.FromFile("image/obama-480p.jpg");
            int iterationsPerTest = 5;
            int testsToRun = 10;
            var iteration = new Func<double>(() =>
            {
                var sw = new Stopwatch();
                sw.Start();
                for (var count = 0; count < iterationsPerTest; count++)
                {
                    Thread.Sleep(1000);
                    _viewFace.FaceDetector(bitmap);
                }
                sw.Stop();

                return sw.ElapsedMilliseconds;
            });

            var averageExecution = Enumerable.Repeat(0, testsToRun).Select(i => iteration()).Average() - 1000;
            bitmap.Dispose();
            Console.WriteLine($"人脸检测{iterationsPerTest * testsToRun}次平均速度：{averageExecution}");
        }`
报错信息如图：
![Uploading image.png…]()

**Comment by View12138** [comment]
可以把 obama-480p.jpg 邮箱发给我吗? 我这边本地测试一下

**Comment by Protears** [comment]
![obama-240p](https://user-images.githubusercontent.com/45806588/102586233-b7abc000-4144-11eb-8df7-741f2cbd5ec3.jpg)
![obama-480p](https://user-images.githubusercontent.com/45806588/102586237-b9758380-4144-11eb-8cbb-3b6519d901d2.jpg)
![obama-720p](https://user-images.githubusercontent.com/45806588/102586242-bbd7dd80-4144-11eb-8fe5-1f945f10753d.jpg)
![obama-1080p](https://user-images.githubusercontent.com/45806588/102586246-c003fb00-4144-11eb-9a09-11ba2ee32689.jpg)

**Comment by Protears** [comment]
图片来源：https://github.com/takuya-takeuchi/FaceRecognitionDotNet/blob/master/examples/Benchmark/obama-480p.jpg

**Comment by Protears** [comment]
> 可以把obama-480p.jpg邮箱发给我吗？我这边本地测试一下

图片来源：https : //github.com/takuya-takeuchi/FaceRecognitionDotNet/blob/master/examples/Benchmark/obama-480p.jpg

**Comment by Protears** [comment]
> 可以把 obama-480p.jpg 邮箱发给我吗? 我这边本地测试一下

测试demo：https://gitee.com/Protear/face-detection-console
