### ISSUE TITLE
app崩溃,FatalExecutionEngineError

### ISSUE THREAD

**Issue by nocanstillbb** [View12138/ViewFaceCore#13]
问题描述:造了个单例, 在wpf控件写dispatcher timer , 在timer的tick事件用这个单例去识别人脸, 总是报FatalExecutionEngineError这个错误直接崩溃了,  线程在viewFace.FaceDetector(mybitmap)这里停住了.用windbg查看了内存堆栈,只有一个实例在执行人脸识别.
单例的代码
veiwfacecore版本:0.3.4
``` 
        public class FaceCaptureViewModel
        {

            public ViewFace viewFace = new ViewFace("./FaceLibraries/model/", (str) => { Debug.WriteLine(str); });
            public static FaceCaptureViewModel Instance = new FaceCaptureViewModel();
            public Action<string> OnFaceBeCapture;
            public FaceCaptureViewModel()
            {
                viewFace.DetectorConfig = new ViewFaceCore.Sharp.Configs.FaceDetectorConfig { FaceSize = 20, MaxWidth = 2000, MaxHeight = 2000, Threshold = 0.9 };
                // 系统默认使用的轻量级识别模型。如果对精度有要求，请切换到 Normal 模式；并下载需要模型文件 放入生成目录的 model 文件夹中
                viewFace.FaceType = FaceType.Normal;
                // 系统默认使用5个人脸关键点。//不建议改动，除非是使用口罩模型。
                viewFace.MarkType = MarkType.Light;

            }

        }


```

调用的代码:
```
                        src = (Bitmap)_currentFrame.Clone();
                        var _result = FaceCaptureViewModel.Instance.viewFace.FaceDetector(src);

```

**Comment by nocanstillbb** [comment]
引发的异常:“System.BadImageFormatException”(位于 Ice.dll 中)
warning: bzip2.dll could not be loaded (likely due to 32/64-bit mismatch). Make sure the directory containing the 64-bit bzip2.dll is in your PATH.
线程 0x4270 已退出，返回值为 0 (0x0)。
托管调试助手 "FatalExecutionEngineError"
运行时遇到了错误。此错误的地址为 0x4df47b12，在线程 0x55dc 上。错误代码为 0xc0000005。此错误可能是 CLR 中的 bug，或者是用户代码的不安全部分或不可验证部分中的 bug。此 bug 的常见来源包括用户对 COM-interop 或 PInvoke 的封送处理错误，这些错误可能会损坏堆栈。

**Comment by nocanstillbb** [comment]
用了emguCV，不崩溃了

**Comment by masgh21** [comment]
Hello @nocanstillbb 
Do you have this error now ?
