### ISSUE TITLE
识别出错

### ISSUE THREAD

**Issue by LymWm** [View12138/ViewFaceCore#17]
调用方法 ViewFace.FaceMark()的时候，，返回的永远都是空数组,精度已经设置的很低了，换了很多张图片问题依旧

**Comment by View12138** [comment]
可以先对照这个例子看看 [Demo](https://github.com/View12138/ViewFaceCoreDemo)

**Comment by LymWm** [comment]
项目需要做一个人脸识别登录，需要完全离线的，这个框架可以做到吗? 担心花时间来学最后又达不到目的

**Comment by View12138** [comment]
> 项目需要做一个人脸识别登录，需要完全离线的，这个框架可以做到吗? 担心花时间来学最后又达不到目的

这个是基于 中科院的 SeetaFace6 ，可以完全离线使用。本项目暂时只支持运行在 Windows 平台
