### ISSUE TITLE
ViewFace在windows下cpu为Intel(R) Pentium(R)时无法使用 

### ISSUE THREAD

**Issue by rain158** [View12138/ViewFaceCore#18]
您好，谢谢你的项目，我使用viewFace.dll文件做了一个浏览器ocx，在AMD和Intel 酷睿CPU下面没有问题，但是在Intel 奔腾CPU下面出现无法加载的情况。谢谢
![image](https://user-images.githubusercontent.com/22168200/111271581-5aa0a700-866c-11eb-8e7b-9bc480d27632.png)

**Comment by View12138** [comment]
定位到你的项目的部署目录，打开` FaceLibraries\x86` 以及 `FaceLibraries\x64` 。把 `tennis.dll` 删除，把 `tennis_pentium.dll` 重命名为 `tennis.dll` 即可。(只针对 Pentium CPU 做这样的处理，并且每次重新部署之后都要做这个操作)

**Comment by rain158** [comment]
非常感谢，测试可以使用
