### ISSUE TITLE
调用活体识别或人脸识别时，摄像头显示界面卡顿

### ISSUE THREAD

**Issue by rain158** [View12138/ViewFaceCore#19]
<img width="627" alt="708897B0-4A85-408b-AE55-8405888650B5" src="https://user-images.githubusercontent.com/22168200/112241429-2f7a1100-8c85-11eb-8106-8fcfd2ebca81.png">
请教个问题，把算法集成到浏览器中时，在调用活体识别方法或者人脸识别方法时，因为识别方法需要时间，页面上显示的画面存在稍微卡顿，想保持显示画面一直流畅，有什么好的解决思路吗？谢谢！

**Comment by View12138** [comment]
- 人脸坐标识别和其它检测的方法分开, 画面上保证一直在获取人脸坐标即可, 在其它检测算法没有完成之前, 可直接丢帧. 
- 如果是浏览器端采集画面,服务端来进行识别的话, 瓶颈可能是网络传输.
