### ISSUE TITLE
图片人脸识别不出来

### ISSUE THREAD

**Issue by daguzt** [View12138/ViewFaceCore#2]
请问为什么开摄像头对准图片能把图片的人脸识别出来，直接传入图片人脸却识别不出来了呢？只是个别图片识别不出来，识别不出来人脸的图片像素也不大。。

**Comment by View12138** [comment]
如果使用的是 0.2.x 版本,可能因为图片像像素格式不同, 导致出现这类问题.  那么建议在 NuGet 中升级到 0.3.3-alpha 版本. [勾选预发行]

**Comment by View12138** [comment]
@daguzt 如果使用的是 0.2.x 版本,可能因为图片像像素格式不同, 导致出现这类问题. 那么建议在 NuGet 中升级到 0.3.3-alpha 版本. [勾选预发行]

**Comment by daguzt** [comment]
> @daguzt 如果使用的是 0.2.x 版本,可能因为图片像像素格式不同, 导致出现这类问题. 那么建议在 NuGet 中升级到 0.3.3-alpha 版本. [勾选预发行]

好的，谢谢！！确实是0.2.x版本。我识别不出人脸的图片是证件照，之前我是调低阈值的，调到0.05可以识别，不过误识别太恐怖了。。，不过我开摄像头对着证件照却可以在阈值默认的0.9的时候识别，我就再new了一个证件照两倍长宽的bitmap，把证件照写在那个bitmap中间，就能在0.9的条件下识别出人脸了。。不知道什么原理。。不过0.9的阈值还是会有误识别的情况，那个人脸置信度起码要大于0.99才行。

**Comment by daguzt** [comment]
> @daguzt 如果使用的是 0.2.x 版本,可能因为图片像像素格式不同, 导致出现这类问题. 那么建议在 NuGet 中升级到 0.3.3-alpha 版本. [勾选预发行]

我现在在使用的是0.3.3-alpha 版本，大多数图片都能识别人脸了，但是还是会有部分图片识别不出来，请问人脸识别有像素大小和图片大小的要求的吗？然后啊，ViewFace.FaceMark和ViewFace.FaceDetector有时候会报System.OutOfMemoryException:“内存不足。” System.OutOfMemoryException:“Exception of type 'System.OutOfMemoryException' was thrown.”这些错误，请问你知道是什么原因吗？最后啊，ViewFace.FaceDetector的cpu占用率很高啊，100%了呀，笔记本测试的话，估计有功耗墙，cpu占用率倒是上不去到100%。。请问这有什么办法解决吗？

**Comment by View12138** [comment]
> 我现在在使用的是0.3.3-alpha 版本，大多数图片都能识别人脸了，但是还是会有部分图片识别不出来，请问人脸识别有像素大小和图片大小的要求的吗？然后啊，ViewFace.FaceMark和ViewFace.FaceDetector有时候会报System.OutOfMemoryException:“内存不足。” System.OutOfMemoryException:“Exception of type 'System.OutOfMemoryException' was thrown.”这些错误，请问你知道是什么原因吗？最后啊，ViewFace.FaceDetector的cpu占用率很高啊，100%了呀，笔记本测试的话，估计有功耗墙，cpu占用率倒是上不去到100%。。请问这有什么办法解决吗？

1. 如果图片过大可能会出现 内存溢出 的问题，比如手机拍摄的照片就普片比较大（分辨率超过 2000x2000，这个也是默认要求的最大图片大小）。这个时候可以采用以下代码解决。
```
using View.Drawing.Extensions;

// 这个方法会帮你把图片按照原比例调整到 1500x1500 内。
Bitmap oldImg = (Bitmap)Image.FromFile(oldImgPath).ChangeSize(new Size(1500,1500));
```

2. CPU 占用的问题，在 [SeetaFace 的文档](http://leanote.com/blog/post/5e7d6cecab64412ae60016ef#title-14) 上有说明，把最小识别人脸从默认20 调整到 80，速度可以提升 16倍。对应的代码如下：
```
ViewFace viewFace = new ViewFace();
viewFace.DetectorConfig = new FaceDetectorConfig() { FaceSize = 80 };
```
