### ISSUE TITLE
ViewFaceCore 是否支持对比两张人脸是否同一个人？

### ISSUE THREAD

**Issue by junbao520** [View12138/ViewFaceCore#20]
ViewFaceCore 是否支持对比两张人脸是否同一个人？

看到了你的api isSelf 没有看到那点输入两张照片的 api

**Comment by View12138** [comment]
支持的
```
float[] face1 = viewFace.Extract(bitmap1);
float[] face2 = viewFace.Extract(bitmap2);
float simi = viewFace.Similarty(face1, face2);
if(viewFace.IsSelf(simi))
{  // 同一个人  
}
else
{  // 不是同一个人
}
```

**Comment by junbao520** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "View12138/ViewFaceCore"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月25日(星期四) 下午2:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [View12138/ViewFaceCor谢谢了！ e] ViewFaceCore 是否支持对比两张人脸是否同一个人？ (#20)





 
支持的
 float[] face1 = viewFace.Extract(bitmap1); float[] face2 = viewFace.Extract(bitmap2); float simi = viewFace.Similarty(face1, face2); if(viewFace.IsSelf(simi)) {  // 同一个人   } else {  // 不是同一个人 }

**Comment by junbao520** [comment]
![112706627-7e6fb280-8ee0-11eb-9f42-31403c480500](https://user-images.githubusercontent.com/20721833/112719402-cbc93f80-8f33-11eb-88e6-b8d2e498339a.png)
d调用算法比对人脸出错！大佬帮忙看看

**Comment by View12138** [comment]
把 模型都下载了, 放到输出目录

**Comment by junbao520** [comment]
放了！


经过测试是 Light 模式会出错，
Normal 模式可以正常运行！&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "View12138/ViewFaceCore"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月29日(星期一) 上午9:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [View12138/ViewFaceCore] ViewFaceCore 是否支持对比两张人脸是否同一个人？ (#20)





 
把 模型都下载了, 放到输出目录

**Comment by View12138** [comment]
```
 // 请使用这样的配置, 不要修改.
ViewFace.FaceType = ViewFaceCore.Sharp.Model.FaceType.Normal;
ViewFace.MarkType = ViewFaceCore.Sharp.Model.MarkType.Light;
```

**Comment by junbao520** [comment]
收到 谢谢！
