### ISSUE TITLE
能编译Linux版本的ViewFace库吗

### ISSUE THREAD

**Issue by withsalt** [View12138/ViewFaceCore#22]
SeetaFace6支持Linux，但是我自己不会C++，也不知道项目中ViewFace能否编译为Linux的动态链接库。可以的话，项目也可以在Linux中使用。

**Comment by View12138** [comment]
> SeetaFace6支持Linux，但是我自己不会C++，也不知道项目中ViewFace能否编译为Linux的动态链接库。可以的话，项目也可以在Linux中使用。

这个版本目前仅支持在 Windows 下运行, 空闲时间正在开发下个版本, 以支持 Linux

**Comment by withsalt** [comment]
感谢
