### ISSUE TITLE
咨询一个Similarity效率问题，比如5000个特征与一张图片的比对。

### ISSUE THREAD

**Issue by jiangliujun** [View12138/ViewFaceCore#24]
不好意思，对这块技术不熟悉，弱弱的咨询个问题。
如果人脸库中有几万张，那一张一张Similarity过去，即便每一次比对只花5ms，最多要比上万张肯定很慢。
有没有办法像数据库查询一样的，对特征数据进行预处理来加快比对效率呢？ 
还是只能用加机器做分布运行解决了？

**Comment by View12138** [comment]
这个是 [SeetaFace6 官方文档](http://leanote.com/blog/post/5e7d6cecab64412ae60016ef#title-21) 上的说法：
> 1比N识别与1比1区别在于，对于现场待识别的人脸，不知道其身份，需要在一个底库中去查询，如果在底库中给出对应识别结果，如果不在底库中，报告未识别。如果业务场景中，确定待识别的人脸一定在底库中，那么就是一个闭集测试，也可以称之为人脸检索。反之，就是开集测试。
> 
> 由描述可以看出，开集场景要比闭集场景更困难，因为要着重考虑误识别率。
> 
> 1比N识别从接口调用上来说，首先需要将底库中的人脸全部提取特征，然后，对现场抓拍到的待识别人脸提取特征，最终使用特征与底库中的特征进行比较选出相似度最高的人脸，这时相似度若超过阈值，则认为识别成功，反之待识别人员不在底库。
> 
> 而常见的1比N识别就是摄像头下的动态人脸识别。这个时候就必要提出我们后面要讲解的模块人脸跟踪和质量评估。
> 
> 这两者在动态人脸识别中用来解决运行效率和精度的问题。首先动态人脸识别系统中，往往待识别人员会再摄像头下运动，并保持一段时间。这个时候需要跟踪从一开始确定，摄像头下现在出现的是一个人。在这个基础上，同一个人只需要识别一次即可。而这个用来识别的代表图片，就是要利用质量评估模块，选出对识别效果最好的一张用来识别。
> 
> 人脸跟踪和质量评估两个方法的配合使用，即避免了每一帧都识别对系统的压力，也通过从多帧图像中选择质量过关且最好的图片来识别，提高了识别精度。

应该只能加机器了
