### ISSUE TITLE
[ERROR]: [src\runtime\workbench.cpp:197]: Input index out of range. with index=0

### ISSUE THREAD

**Issue by st7yws** [View12138/ViewFaceCore#4]
.NET Core项目下, 多次进行检测图片中的人脸之后就提示越界然后程序终止.

**Comment by st7yws** [comment]
通过将ViewFace设置为全局静态之后不会再报越界了,可以执行更多次的识别,但是出现了新的问题.

程序直接终止,并报出
`Fatal error. Internal CLR error. (0x80131506)`

查看日志,看不出是哪里的问题

**Comment by View12138** [comment]
> .NET Core项目下, 多次进行检测图片中的人脸之后就提示越界然后程序终止.

在整个识别的过程中，Bitmap 不能被释放。可以考虑用 Image.Clone() 来解决越界的问题，而不是全局静态遍历。
