### ISSUE TITLE
识别后能不能同一张人脸形成一个faceid，以用来做人脸登录呢？

### ISSUE THREAD

**Issue by fayuanliu** [View12138/ViewFaceCore#6]
如题

**Comment by View12138** [comment]
> 识别后能不能同一张人脸形成一个faceid，以用来做人脸登录呢？

可以把 `FaceDetector ` 方法替换成 `FaceTrack` , 返回结果会多一个 Pid , 在多个人脸同时识别到时, 可以使用这个 Pid 来追踪不同的人脸. 不知道这个能都满足你的需求 ?

**Comment by fayuanliu** [comment]
如果是同是同一个人脸信息，pid是一样的么？如果不一样，可能满足不了

**Comment by View12138** [comment]
> 如果是同是同一个人脸信息，pid是一样的么？如果不一样，可能满足不了

在每一次的检测中, 只要人脸一直都被检测到, 那么人脸的 Pid 就不会变, 一旦中途某一次检测时这个人脸离开,那当这个人脸再次出现时就会为其分配新的 Pid , 而不是之前的 Pid .

**Comment by fayuanliu** [comment]
明白，那可能不太适合，我是想用户先通过账户密码登录，然后进行人脸采集，下一次可直接通过人脸登录

**Comment by View12138** [comment]
- 可以将人脸特征码和账户关联 , 登录过之后要在客户端记住当前账户 , 这样下次登录时需要先选择账户, 然后免密识别人脸, 去和之前采集的人脸做对比 . 
- 如果不记住账账户 , 就只能每次拿到人脸特征都去全量匹配然后查找账户 ( 但是这样做可能会存在很大的效率问题 , 特别时当账户数量较多时 )

**Comment by fayuanliu** [comment]
嗯，谢谢，我先用方案一，先知道是哪个用户，再比较人脸信息与该账户一至
