### ISSUE TITLE
SeetaFace6二进制文件地址是空的

### ISSUE THREAD

**Issue by neonleo** [View12138/ViewFaceCore#63]
SeetaFace6
二进制文件地址
https://github.com/ViewFaceCore/SeetaFace6OpenBinary/releases

進入後,什麼都沒有.

**Comment by withsalt** [comment]
未发布，稍等几天。

**Comment by withsalt** [comment]
已上传。

**Comment by neonleo** [comment]
> 已上传。

萬分感謝。
