### ISSUE TITLE
[Bug]阿里云服务器运行报错

### ISSUE THREAD

**Issue by liaozb** [View12138/ViewFaceCore#67]
![image](https://user-images.githubusercontent.com/12622501/193181372-af3de92c-baff-4252-9cb3-26032df02a44.png)

**Comment by liaozb** [comment]
![image](https://user-images.githubusercontent.com/12622501/193181513-d9c4f7dd-a8ca-4415-a76c-4d1ecb513332.png)

**Comment by withsalt** [comment]
用的系统版本？
参考解决方案：https://zhuanlan.zhihu.com/p/559791450

**Comment by liaozb** [comment]
@withsalt 感谢
