### ISSUE TITLE
[Feature]请问centos支持嘛？

### ISSUE THREAD

**Issue by mingyangzhu** [View12138/ViewFaceCore#68]
国内linux服务 centos 的比列还是挺多的，请问这个库可以部署到centos服务器上嘛？

ps ：这个库是我们发现最好的人脸识别库，感谢作者。

**Comment by neonleo** [comment]
我覺得可以先試試套件中的asp.net core 範例，應該是可以的。

**Comment by withsalt** [comment]
centos 8 stream以上理论上直接支持，centos 7 过于老旧，可能有些麻烦，不推荐。

**Comment by mingyangzhu** [comment]
> centos 8 stream以上理论上直接支持，centos 7 过于老旧，可能有些麻烦，不推荐。

好的。但是目前企业用的版本大部分都是centos7的。我先测试下,测试结果，我再做个反馈。

**Comment by mingyangzhu** [comment]
反馈结果：centos7 的glibc 版本过低，识别库所需要的版本是2.29  目前centos7最高支持2.27。需要升级linux底层的编译库。的确支持起来比较麻烦。

**Comment by mingyangzhu** [comment]
抛出的异常：
Unable to load shared library '/var/wwwroot/kd/intranet_proxy/viewfacecore/linux/x64/libSeetaAuthorize.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /var/wwwroot/kd/intranet_proxy/viewfacecore/linux/x64/libSeetaAuthorize.so)
System.TypeInitializationException: The type initializer for 'ViewFaceCore.Native.ViewFaceNative' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library '/var/wwwroot/kd/intranet_proxy/viewfacecore/linux/x64/libSeetaAuthorize.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /var/wwwroot/kd/intranet_proxy/viewfacecore/linux/x64/libSeetaAuthorize.so)
   at System.Runtime.InteropServices.NativeLibrary.LoadFromPath(String libraryName, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.Load(String libraryPath)
   at ViewFaceCore.Native.ViewFaceNative..cctor()

**Comment by withsalt** [comment]
> 反馈结果：centos7 的glibc 版本过低，识别库所需要的版本是2.29 目前centos7最高支持2.27。需要升级linux底层的编译库。的确支持起来比较麻烦。

这是其中一个原因，还有就是图形组件SkiaSharp对CentOS支持也不是很好。

**Comment by withsalt** [comment]
centos 7上面推荐使用docker，我这边测试莫得问题。
```
#先按照指示安装.net sdk
#https://learn.microsoft.com/zh-cn/dotnet/core/install/linux-centos

#创建并信任证书
dotnet dev-certs https -ep ${HOME}/.aspnet/https/default_aspnetapp.pfx -p 123456
dotnet dev-certs https --trust

#拉取ViewFaceCore源码
git clone https://github.com/ViewFaceCore/ViewFaceCore -b dev
cd ViewFaceCore/src

#构建docker镜像
docker build -t viewfacecore_example_webapp:latest -f ./Examples/ViewFaceCore.Example.WebApp/Dockerfile .

#运行docker镜像
docker run --restart=always -it \
 --name=viewfacecore_example_webapp \
 -p 80:80 -p 443:443 \
 -e ASPNETCORE_URLS="https://+;http://+" \
 -e ASPNETCORE_Kestrel__Certificates__Default__Password="123456" \
 -e ASPNETCORE_Kestrel__Certificates__Default__Path=/https/default_aspnetapp.pfx \
 -v ${HOME}/.aspnet/https:/https/ \
 -d viewfacecore_example_webapp:latest

#然后浏览器访问 https://<docker所在机器IP>
```

**Comment by mingyangzhu** [comment]
> 



> centos 7上面推荐使用docker，我这边测试莫得问题。
> 
> ```
> #先按照指示安装.net sdk
> #https://learn.microsoft.com/zh-cn/dotnet/core/install/linux-centos
> 
> #创建并信任证书
> dotnet dev-certs https -ep ${HOME}/.aspnet/https/default_aspnetapp.pfx -p 123456
> dotnet dev-certs https --trust
> 
> #拉取ViewFaceCore源码
> git clone https://github.com/ViewFaceCore/ViewFaceCore -b dev
> cd ViewFaceCore/src
> 
> #构建docker镜像
> docker build -t viewfacecore_example_webapp:latest -f ./Examples/ViewFaceCore.Example.WebApp/Dockerfile .
> 
> #运行docker镜像
> docker run --restart=always -it \
>  --name=viewfacecore_example_webapp \
>  -p 80:80 -p 443:443 \
>  -e ASPNETCORE_URLS="https://+;http://+" \
>  -e ASPNETCORE_Kestrel__Certificates__Default__Password="123456" \
>  -e ASPNETCORE_Kestrel__Certificates__Default__Path=/https/default_aspnetapp.pfx \
>  -v ${HOME}/.aspnet/https:/https/ \
>  -d viewfacecore_example_webapp:latest
> 
> #然后浏览器访问 https://<docker所在机器IP>
> ```

好的，感谢指导。

**Comment by wu-xiaohua** [comment]
没有看到./Examples/ViewFaceCore.Example.WebApp/Dockerfile 文件，是没有上传吗？
