### ISSUE TITLE
[Bug]win10 64位操作系统，.net 6 控制台应用程序，new FaceDetector()异常退出，没有任何异常信息

### ISSUE THREAD

**Issue by lovemory** [View12138/ViewFaceCore#69]
**简明描述**
开发环境：win10,64位，
开发工具：vs2022 ,
新建控制台项目，
添加nuget程序包：ViewFaceCore  ， ViewFaceCore.all_models  ， ViewFaceCore.Extension.SkiaSharp  , ViewFaceCore.runtime.win.x64

Program.cs 代码如下：
```

using SkiaSharp;
using System;
using ViewFaceCore;
using ViewFaceCore.Core;
using ViewFaceCore.Model;
internal class Program
{
    private readonly static string imagePath = @"images/Jay_3.jpg";
    private static void Main(string[] args)
    {
        Console.WriteLine("Hello, World!");
        try
        {
            using var bitmap = SKBitmap.Decode(imagePath);
            using FaceDetector faceDetector = new FaceDetector();
            FaceInfo[] infos = faceDetector.Detect(bitmap);
            Console.WriteLine($"识别到的人脸数量：{infos.Length} 个人脸信息：\n");
            Console.WriteLine($"No.\t人脸置信度\t位置信息");
            for (int i = 0; i < infos.Length; i++)
            {
                Console.WriteLine($"{i}\t{infos[i].Score:f8}\t{infos[i].Location}");
            }
        }
        catch (Exception ex)
        {

            Console.WriteLine(ex.Message);
        }

        Console.WriteLine("END!");
        Console.ReadKey();
    }
}


```
**重现步骤**
按如上描述，编写代码， 运行。
在
 using FaceDetector faceDetector = new FaceDetector();
这样一行异常退出， 没有捕获到错误。
控制台输出如下：
Hello, World!

F:\aaaaaaaaaaaaaaaaaaaa\人脸识别\ViewFaceCore_Test\ViewFaceCore_Test\bin\Debug\net6.0-windows\ViewFaceCore_Test.exe (进 程 16188)已退出，代码为 -1073741795。
要在调试停止时自动关闭控制台，请启用“工具”->“选项”->“调试”->“调试停止时自动关闭控制台”。
按任意键关闭此窗口. . .

**开发环境**
 - 目标框架: [ .net6-windows]
 - 项目类型 [控制台应用]

**相关包清单**
-ViewFaceCore 
-ViewFaceCore.all_models
-ViewFaceCore.Extension.SkiaSharp 
-ViewFaceCore.runtime.win.x64

**运行环境**
 - 操作系统: [ Windows 10 专业版]
 - 系统类型: [ 64 位操作系统, 基于 x64 的处理器]
 - 处理器: [QuadCore Intel Core i7-860, 2800 MHz (21 x 133)]

**附件**

**Comment by withsalt** [comment]
QuadCore Intel Core i7-860 不支持AVX指令集，可以安装0.4的预览版包，然后设置指令集为SSE
参考：
https://github.com/ViewFaceCore/ViewFaceCore/tree/main#4432-%E7%89%B9%E5%AE%9A%E6%8C%87%E4%BB%A4%E9%9B%86%E6%94%AF%E6%8C%81

**Comment by lovemory** [comment]
> QuadCore Intel Core i7-860 不支持AVX指令集，可以安装0.4的预览版包，然后设置指令集为SSE 参考： https://github.com/ViewFaceCore/ViewFaceCore/tree/main#4432-%E7%89%B9%E5%AE%9A%E6%8C%87%E4%BB%A4%E9%9B%86%E6%94%AF%E6%8C%81
把下面三个升级到最新的预览版
ViewFaceCore 0.4.0-alpha2
ViewFaceCore.Extension.SkiaSharp    0.4.0-alpha2
ViewFaceCore.runtime.win.x64   6.0.8-alpha2
这个问题解决， 多谢。
 差点让我还没有入门就放弃了。
