### ISSUE TITLE
[Feature] 人臉比對返回相似度

### ISSUE THREAD

**Issue by neonleo** [View12138/ViewFaceCore#70]
你好,
在我使用ViewFaceCore测试过程中, 使用千个脸孔做训练，一个脸孔大概有20张至200张现实生活照做比对。
人脸识别的准确度是中上水准的，大概90%，但想调整细节或参数提升到97%。

但觉得比对後，回调的[QualityResult](https://github.com/ViewFaceCore/ViewFaceCore/blob/dev/src/ViewFaceCore/Models/QualityResult.cs) 中的Score ，比较奇怪。
如下图，
source_key 是训练脸孔的ID, count 是正确比对的总数， avg_quality_score是平均的QualityResult.Score
![image](https://user-images.githubusercontent.com/31003301/201565171-fdb69d2a-0c36-4e74-b48c-65f38d0773d2.png)

即使一些较高辨识率的脸孔，quality_score平均值也是普普，参考过[SeetaFace6 入门教程](http://leanote.com/blog/post/5e7d6cecab64412ae60016ef) ，quality result的score似乎只是传入图像的质量评估。

相似度计算的函数:
`#include <seeta/FaceRecognizer.h>
#include <memory>
float compare(seeta::FaceRecognizer *fr,
        const std::shared_ptr<float> &feat1,
        const std::shared_ptr<float> &feat2) {
    return fr->CalculateSimilarity(feat1.get(), feat2.get());
}`

应该是有返回Similarity的。
故希望大大，可以考虑在辨识後，加入回传Similarity，可以在前端二次判斷是否通過。
谢谢。

PS: 除了ViewFaceCore，近期小弟一直测试另一个在GitHub的热门人脸辨识项目[CompreFace](https://github.com/exadel-inc/CompreFace)，准确度跟ViewFaceCore差不多，但基於本人是.NET魂，還是主要研究ViewFaceCore和Java版SeetaFace6。

**Comment by withsalt** [comment]
> 故希望大大，可以考虑在辨识後，加入回传Similarity，可以在前端二次判斷是否通過。

这句话不是很懂，FaceRecognizer里面有Compare方法，能返回相似度。

**Comment by neonleo** [comment]
> > 故希望大大，可以考虑在辨识後，加入回传Similarity，可以在前端二次判斷是否通過。
> 
> 这句话不是很懂，FaceRecognizer里面有Compare方法，能返回相似度。

噢，是的, 一直在看IsSelf() 方法 , 沒注意到Compare() 方法 👍
