### ISSUE TITLE
[Bug]System.PlatformNotSupportedException: Unsupported system type: Linux 5.4.0-90-generic 

### ISSUE THREAD

**Issue by lovemory** [View12138/ViewFaceCore#71]
**简明描述**
开发环境：win10,64位，
开发工具：vs2022 ,
新建控制台项目，
添加nuget程序包：ViewFaceCore ， ViewFaceCore.all_models ， ViewFaceCore.Extension.SkiaSharp , ViewFaceCore.runtime.win.x64
编译运行在ubuntu.

`FaceDetector faceDetector = new FaceDetector();`

代码抛出异常

The type initializer for 'ViewFaceCore.Native.ViewFaceNative' threw an exception.  
InnerException:
System.PlatformNotSupportedException: Unsupported system type: Linux 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021\n   at ViewFaceCore.Native.ViewFaceNative..cctor()"

**重现步骤**
编译运行在ubuntu.

**开发环境**
- 目标框架: [ .NET Framework 4.7.2]
- 项目类型 [控制台应用]

**相关包清单**
- ViewFaceCore 0.4.0-alpha2
- ViewFaceCore.all_models 6.0.7
- ViewFaceCore.Extension.SkiaSharp 0.4.0-alpha2
- ViewFaceCore.runtime.win.x64 6.0.8-alpha2
- ViewFaceCore.runtime.ubuntu.20.04.x64 6.0.8-alpha2

**运行环境**
- 操作系统: ubuntu
- 系统类型: : Linux VM-20-2-ubuntu 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 - GNU/Linux
- 处理器: : Intel(R) Xeon(R) Platinum 8255C CPU @ 2.50GHz

**附件**

**Comment by withsalt** [comment]
.NET Framework 4.7.2在ubuntu运行吗？

**Comment by lovemory** [comment]
### 简明描述

- 开发环境：win10,64位，

- 开发工具：vs2022 ,

新建控制台项目，
添加nuget程序包：ViewFaceCore ， ViewFaceCore.all_models ， ViewFaceCore.Extension.SkiaSharp , ViewFaceCore.runtime.win.x64
编译运行在ubuntu.

FaceDetector faceDetector = new FaceDetector();

代码抛出异常

 root@VM-20-2-ubuntu:~/temp/linux-x64# ./ViewFaceCore_Test
Hello, World!
[内部日志]CPU only support SSE2 instruction, will use tennis_pentium.
The type initializer for 'ViewFaceCore.Native.ViewFaceNative' threw an exception.
END!


### 重现步骤
代码见附件，
vs2022 工程发布设置：目标框架.net 6.0 目标运行时：linux-x64
上传发布包到ubuntu运行。

###开发环境

- 目标框架: [ .NET 6.0]

- 项目类型 [控制台应用]

- 相关包清单

ViewFaceCore 0.4.0-alpha2
ViewFaceCore.all_models 6.0.7
ViewFaceCore.Extension.SkiaSharp 0.4.0-alpha2
ViewFaceCore.runtime.win.x64 6.0.8-alpha2
ViewFaceCore.runtime.ubuntu.20.04.x64 6.0.8-alpha2
###运行环境

- 操作系统: ubuntu

- 系统类型: : Linux VM-20-2-ubuntu 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 - GNU/Linux

- 处理器: : Intel(R) Xeon(R) Platinum 8255C CPU @ 2.50GHz

### 附件

[Program.zip](https://github.com/ViewFaceCore/ViewFaceCore/files/10023432/Program.zip)

**Comment by withsalt** [comment]
如果CPU支持AVX2指令集的话，可以去掉 `GlobalConfig.SetX86Instruction(X86Instruction.SSE2);` 这玩意儿在linux上面支持不是很好。
```
root@ubuntu-dev:~/publish# sudo ./ConsoleApp2 
Hello, World!
识别到的人脸数量：1 个人脸信息：

No.	人脸置信度	位置信息
0	0.99988818	{X:193, Y:248, Width:334, Height:418}
耗时：120ms
{Score:0.9998882, Location:{X:193, Y:248, Width:334, Height:418}}
输出图片已保存至：images/Jay_out.jpg
开始特征值比较
识别到的人脸是否为同一人：True，对比耗时：1266ms

END!
root@ubuntu-dev:~/publish# uname -a
Linux ubuntu-dev 5.4.0-132-generic #148-Ubuntu SMP Mon Oct 17 16:02:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
root@ubuntu-dev:~/publish# 
```

**Comment by lovemory** [comment]
感谢 [withsalt](https://github.com/withsalt) ，修改了一下，可以使用了。
root@VM-20-2-ubuntu:~/temp/linux-x64# ./ViewFaceCore_Test
Hello, World!
识别到的人脸数量：1 个人脸信息：

No.     人脸置信度      位置信息
0       0.99988818      {X:193, Y:248, Width:334, Height:418}
耗时：686ms
{Score:0.9998882, Location:{X:193, Y:248, Width:334, Height:418}}
输出图片已保存至：images/Jay_out.jpg
开始特征值比较
识别到的人脸是否为同一人：True，对比耗时：1903ms

END!

耗时那么长，如果对比10张图片，那不是需要1903ms*10 接近20秒？

**Comment by withsalt** [comment]
对比性能和CPU单核性能挂钩，多张图片对比建议对象池和多线程。有大量数据需要对比的话，可以使用GPU计算（默认情况没有支持，需要手动替换一下库），能大幅度提高性能。
