### ISSUE TITLE
口罩识别报  ERROR: [FaceDetector.cpp:201]: Model: /prior_box must be dict 错

### ISSUE THREAD

**Issue by ywx666** [View12138/ViewFaceCore#8]
![image](https://user-images.githubusercontent.com/23479854/95647975-6957c080-0b06-11eb-9307-111228827604.png)
请问这种怎么处理呢？ @View12138

**Comment by View12138** [comment]
这个问题可能得参考SeetaFace的官方文档了，我也没遇到过
