### ISSUE TITLE
ViewFace.DLL在其他电脑无法正常工作

### ISSUE THREAD

**Issue by netleike** [View12138/ViewFaceCore#9]
ViewFace.DLL在其他电脑无法正常工作,部分电脑又可以,VC++从2010-2019全部装了也没用,源码也MT方式编译了,麻烦告知下需要什么库

**Comment by View12138** [comment]
除了SeetaFace以外没有别的库了，部分电脑可以说明应该是没问题的，那不能运行的电脑考虑是否是指令集不支持等原因
